### ISSUE TITLE
DNS callback error

### ISSUE THREAD

**Issue by hackforus** [fullhunt/log4j-scan#78]
Traceback (most recent call last):
  File "/Users/darkcode/src/log4j-scan/log4j-scan.py", line 362, in <module>
    main()
  File "/Users/darkcode/src/log4j-scan/log4j-scan.py", line 332, in main
    dns_callback = Interactsh()
  File "/Users/darkcode/src/log4j-scan/log4j-scan.py", line 195, in __init__
    self.register()
  File "/Users/darkcode/src/log4j-scan/log4j-scan.py", line 206, in register
    raise Exception("Can not initiate interact.sh DNS callback client")
Exception: Can not initiate interact.sh DNS callback client

any something wrong with this?

**Comment by JonAnder83** [comment]
Same issue here on Ubuntu 20.04

**Comment by divadiow** [comment]
same :(

**Comment by mazen160** [comment]
It means that the DNS callback provider is down, or you can not connect to the DNS callback provider due to networking issues. You can use an different DNS Callback provider (eg.. with `--dns-callback-provider dnslog.cn`), or you can use a custom DNS callback host with ` --custom-dns-callback-host`.
